/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufla.dcc.ppoo.gui;

import br.ufla.dcc.ppoo.servicos.GerenciadorFilmes;
import br.ufla.dcc.ppoo.servicos.GerenciadorListasDeFilmes;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arlen
 */
public class TelaMinhasListasFilmes extends javax.swing.JDialog {
    
    
    ListasTableModel modelListas;
    FilmesTableModel modelFilmesDaLista;
    GerenciadorListasDeFilmes gerenciadorListasDeFilmes;
    GerenciadorFilmes gerenciadorFilmes;
    /**
     * Creates new form TelaMinhasListasFilmes
     */
    public TelaMinhasListasFilmes(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        gerenciadorFilmes = new GerenciadorFilmes();
        gerenciadorListasDeFilmes = new GerenciadorListasDeFilmes();
        construirTabelas();
        initComponents();
        preparaComponenteInicial();
    }
    
    private void construirTabelas() throws SQLException {
        modelListas = new ListasTableModel(gerenciadorListasDeFilmes.buscarListasUsuario());
        modelFilmesDaLista = new FilmesTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbListas = new javax.swing.JTable();
        btnNovaLista = new javax.swing.JButton();
        btnEditarLista = new javax.swing.JButton();
        btnDeletarLista = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbFilmesDaLista = new javax.swing.JTable();
        lbTabelaFilmes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Listas");

        tbListas.setModel(modelListas);
        tbListas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListas);

        btnNovaLista.setText("Nova");

        btnEditarLista.setText("Editar");

        btnDeletarLista.setText("Deletar");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        tbFilmesDaLista.setModel(modelFilmesDaLista);
        jScrollPane3.setViewportView(tbFilmesDaLista);

        lbTabelaFilmes.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lbTabelaFilmes.setText("Filmes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTabelaFilmes)
                .addGap(280, 280, 280))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lbTabelaFilmes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovaLista)
                            .addComponent(btnEditarLista)
                            .addComponent(btnDeletarLista)
                            .addComponent(btnFechar)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbListasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListasMouseClicked
        try {
            preencheTabelaFilmes();
            preparaComponenteSelecionaLista();
        } catch (SQLException ex) {
            Logger.getLogger(TelaMinhasListasFilmes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbListasMouseClicked

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMinhasListasFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMinhasListasFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMinhasListasFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMinhasListasFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaMinhasListasFilmes dialog;
                try {
                    dialog = new TelaMinhasListasFilmes(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaMinhasListasFilmes.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletarLista;
    private javax.swing.JButton btnEditarLista;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovaLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbTabelaFilmes;
    private javax.swing.JTable tbFilmesDaLista;
    private javax.swing.JTable tbListas;
    // End of variables declaration//GEN-END:variables
    private void preencheTabelaFilmes() throws SQLException {
        modelFilmesDaLista.atualizarListaFilmes(gerenciadorListasDeFilmes.buscarListasUsuario().get(tbListas.getSelectedRow()).getFilmes());
    }
    
    private void preparaComponenteInicial(){
        btnDeletarLista.setEnabled(false);
        btnNovaLista.setEnabled(true);
        btnFechar.setEnabled(true);
        btnEditarLista.setEnabled(false);
    }
    
    private void preparaComponenteSelecionaLista(){
        btnDeletarLista.setEnabled(true);
        btnNovaLista.setEnabled(true);
        btnFechar.setEnabled(true);
        btnEditarLista.setEnabled(true);
    }
}
