/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufla.dcc.ppoo.gui;

import br.ufla.dcc.ppoo.modelo.Lista;
import br.ufla.dcc.ppoo.seguranca.SessaoUsuario;
import br.ufla.dcc.ppoo.servicos.GerenciadorFilmes;
import br.ufla.dcc.ppoo.servicos.GerenciadorListasDeFilmes;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arlen
 */
public class TelaListasPublicas extends javax.swing.JDialog {
    
    
    ListasTableModel modelListas;
    FilmesTableModel modelFilmesDaLista;
    GerenciadorListasDeFilmes gerenciadorListasDeFilmes;
    GerenciadorFilmes gerenciadorFilmes;
    /**
     * Creates new form TelaMinhasListasFilmes
     */
    public TelaListasPublicas(java.awt.Frame parent, boolean modal, List<Lista> listas) throws SQLException {
        super(parent, modal);
        gerenciadorFilmes = new GerenciadorFilmes();
        gerenciadorListasDeFilmes = new GerenciadorListasDeFilmes();
        construirTabelas(listas);
        initComponents();
        preparaComponenteInicial();
    }
    
    private void construirTabelas(List<Lista> ls) throws SQLException {
        modelListas = new ListasTableModel(ls);
        modelFilmesDaLista = new FilmesTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbListas = new javax.swing.JTable();
        btnImportar = new javax.swing.JButton();
        btnDetalhes = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbFilmesDaLista = new javax.swing.JTable();
        lbTabelaFilmes = new javax.swing.JLabel();
        btnComentar = new javax.swing.JButton();
        btnAvaliar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Listas");

        tbListas.setModel(modelListas);
        tbListas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListas);

        btnImportar.setText("Importar");

        btnDetalhes.setText("Detalhes");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        tbFilmesDaLista.setModel(modelFilmesDaLista);
        jScrollPane3.setViewportView(tbFilmesDaLista);

        lbTabelaFilmes.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lbTabelaFilmes.setText("Filmes");

        btnComentar.setText("Comentar");

        btnAvaliar.setText("Avaliar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnComentar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAvaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(lbTabelaFilmes)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(lbTabelaFilmes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnImportar)
                            .addComponent(btnDetalhes)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnComentar)
                            .addComponent(btnAvaliar))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbListasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListasMouseClicked
        try {
            preencheTabelaFilmes();
            if(SessaoUsuario.obterInstancia().estahLogado())
                preparaComponenteSelecionaLista();
        } catch (SQLException ex) {
            Logger.getLogger(TelaMinhasListasFilmes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbListasMouseClicked

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        
    }//GEN-LAST:event_btnDetalhesActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListasPublicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListasPublicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListasPublicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListasPublicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaListasPublicas dialog;
                try {
                    dialog = new TelaListasPublicas(new javax.swing.JFrame(), true, null);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaListasPublicas.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliar;
    private javax.swing.JButton btnComentar;
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnImportar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbTabelaFilmes;
    private javax.swing.JTable tbFilmesDaLista;
    private javax.swing.JTable tbListas;
    // End of variables declaration//GEN-END:variables
    private void preencheTabelaFilmes() throws SQLException {
        modelFilmesDaLista.atualizarListaFilmes(modelListas.buscarLista(tbListas.getSelectedRow()).getFilmes());
    }
    
    private void preparaComponenteInicial(){
        btnImportar.setEnabled(false);
        btnDetalhes.setEnabled(false);
        btnComentar.setEnabled(false);
        btnAvaliar.setEnabled(false);
        
        modelFilmesDaLista.limpar();
    }
    
    private void preparaComponenteSelecionaLista(){
        btnImportar.setEnabled(true);
        btnDetalhes.setEnabled(true);
        btnComentar.setEnabled(true);
        btnAvaliar.setEnabled(true);
    }
}
